FROM node:24-slim

ARG BASE_ID
ENV BASE_ID=$BASE_ID

ARG IN_TABLE_NAME
ENV IN_TABLE_NAME=$IN_TABLE_NAME

ARG OUT_TABLE_NAME
ENV OUT_TABLE_NAME=$OUT_TABLE_NAME

ARG EMAIL_SERVICE
ENV EMAIL_SERVICE=$EMAIL_SERVICE

ARG SENDER_EMAIL
ENV SENDER_EMAIL=$SENDER_EMAIL

ARG SENDER_PASSWORD
ENV SENDER_PASSWORD=$SENDER_PASSWORD

ARG RECEIVER_EMAIL
ENV RECEIVER_EMAIL=$RECEIVER_EMAIL

WORKDIR /app

COPY . .

RUN npm install

EXPOSE 3000